# Generated by Django 3.2.13 on 2023-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
